### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by TheBlueFireFox** [TheBlueFireFox/Chip8#6]
- [x] Implement Keyboard
   - [X] mapping
   - [x] adapter callback from JS
- [x]  rework chip timers, so that they return the timer implementation on init.
   - [x] split timers 
       - [x] into value holder `Send`
       - [x] into worker holder `Send` (achived via memory leak)
   - [x]  chip wrapper with pub methods to internal chip impl and holding the timers
